=== langehk/projectweek7/data/authors.xsd
<?xml version="1.0" standalone="yes"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:complexType name="authorList">
        <xs:sequence>
            <xs:element name="author" type="myAuthors" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="myAuthors">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="birthyear" type="xs:string" />
            <xs:element name="deathyear" type="xs:string"  minOccurs="0" maxOccurs="1"/>
            <xs:element name="birthplace" type="xs:string" />
            <xs:element name="country" type="xs:string" />
            <xs:element name="language" type="xs:string" />
            <xs:element name="bio" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="authors" type="authorList" />
</xs:schema>

=== langehk/projectweek7/data/authors.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<authors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="authors.xsd">
  <author>
    <name>Ian Lloyd</name>
    <birthyear>1995</birthyear>
    <deathyear>2020</deathyear>
    <birthplace>London</birthplace>
    <country>England</country>
    <language>en</language>
    <bio>Han var en god forfatter</bio>
  </author>
  <author>
    <name>John Smith</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>New York</birthplace>
    <country>USA</country>
    <language>en</language>
    <bio>Han er en god forfatter</bio>
  </author>
  <author>
    <name>Pia</name>
    <birthyear>1850</birthyear>
    <deathyear>1940</deathyear>
    <birthplace>Esbjerg</birthplace>
    <country>Denmark</country>
    <language>DK</language>
    <bio>123</bio>
  </author>
</authors>

=== langehk/projectweek7/data/author.xml
<?xml version="1.0" standalone="no"?>

<?xml-stylesheet type="text/xsl" href="author.xsl"?>
<authors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="authors.xsd">
    <author>
        <name>Ian Lloyd</name>
        <birthyear>1995</birthyear>
        <deathyear>2020</deathyear>
        <birthplace>London</birthplace>
        <country>England</country>
        <language>en</language>
        <bio>Han var en god forfatter</bio>
        
    </author>

    <author>
        <name>John Smith</name>
        <birthyear>1990</birthyear>
        <deathyear></deathyear>
        <birthplace>New York</birthplace>
        <country>USA</country>
        <language>en</language>
        <bio>Han er en god forfatter</bio>
        
    </author>
    
</authors>

=== langehk/projectweek7/data/authorOLD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<authors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authors.xsd" 
xsl:noNamespaceSchemaLocation="author.xsl">

  <author>
    <name>Ian Lloyd</name>
    <birthyear>1995</birthyear>
    <deathyear>2020</deathyear>
    <birthplace>London</birthplace>
    <country>England</country>
    <language>en</language>
    <bio>Han var en god forfatter</bio>
  </author>
  <author>
    <name>John Smith</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>New York</birthplace>
    <country>USA</country>
    <language>en</language>
    <bio>Han er en god forfatter</bio>
  </author>
  <author>
    <name>Nadia Skau</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>Sønderborg</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Mega awesome</bio>
  </author>
  <author>
    <name>Morten Due</name>
    <birthyear>1998</birthyear>
    <deathyear/>
    <birthplace>Vamdrup</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Næsten awesome</bio>
  </author>
  <author>
    <name>Morten Højrup</name>
    <birthyear>1996</birthyear>
    <deathyear/>
    <birthplace>Esbjerg</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Totalt nørdet</bio>
  </author>
  <author>
    <name>Niels' kat</name>
    <birthyear>2000</birthyear>
    <deathyear/>
    <birthplace>Århus</birthplace>
    <country>Danmark</country>
    <language>Kinesisk</language>
    <bio>Kat</bio>
  </author>
  <author>
    <name>Niels' kat</name>
    <birthyear>2005</birthyear>
    <deathyear/>
    <birthplace>Århus</birthplace>
    <country>Danmark</country>
    <language>Fransk</language>
    <bio>Kat</bio>
  </author>
  <author>
    <name>Konrad</name>
    <birthyear>2015</birthyear>
    <deathyear/>
    <birthplace>Holstrebro</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Vuf</bio>
  </author>
  <author>
    <name>Chris</name>
    <birthyear>1985</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Hvem er det</bio>
  </author>
  <author>
    <name>Erik</name>
    <birthyear>1980</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Tysk</language>
    <bio>Glem det</bio>
  </author>
  <author>
    <name>Bella</name>
    <birthyear>1889</birthyear>
    <deathyear>1989</deathyear>
    <birthplace>Skagen</birthplace>
    <country>Danmark</country>
    <language>Norsk</language>
    <bio>Bella var sød</bio>
  </author>
  <author>
    <name>Arthur</name>
    <birthyear>1776</birthyear>
    <deathyear>1826</deathyear>
    <birthplace>Odense</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Hey du</bio>
  </author>
</authors>

=== langehk/projectweek7/data/sortAuthor.xml
<?xml version="1.0" standalone="no"?> <?xml-stylesheet type="text/xsl" href="sortAuthor.xsl"?><authors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="authors.xsd">
  <author>
    <name>Ian Lloyd</name>
    <birthyear>1995</birthyear>
    <deathyear>2020</deathyear>
    <birthplace>London</birthplace>
    <country>England</country>
    <language>en</language>
    <bio>Han var en god forfatter</bio>
  </author>
  <author>
    <name>John Smith</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>New York</birthplace>
    <country>USA</country>
    <language>en</language>
    <bio>Han er en god forfatter</bio>
  </author>
  <author>
    <name>Nadia Skau</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>Sønderborg</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Mega awesome</bio>
  </author>
  <author>
    <name>Nadia Skau</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace/>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Mega awesome</bio>
  </author>
  <author>
    <name>Morten Due</name>
    <birthyear>1998</birthyear>
    <deathyear/>
    <birthplace>Vamdrup</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Næsten awesome</bio>
  </author>
  <author>
    <name>Morten Due</name>
    <birthyear>1998</birthyear>
    <deathyear/>
    <birthplace>Vamdrup</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Næsten awesome</bio>
  </author>
  <author>
    <name>Morten Højrup</name>
    <birthyear>1996</birthyear>
    <deathyear/>
    <birthplace>Esbjerg</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Totalt nørdet</bio>
  </author>
  <author>
    <name>Louise</name>
    <birthyear>1986</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Lærer</bio>
  </author>
  <author>
    <name>Louise</name>
    <birthyear>1986</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Lærer</bio>
  </author>
  <author>
    <name>Louise</name>
    <birthyear>1986</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Lærer</bio>
  </author>
  <author>
    <name>Nadia Skau</name>
    <birthyear>1990</birthyear>
    <deathyear/>
    <birthplace>Sønderborg</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Lærer</bio>
  </author>
  <author>
    <name>Nadia Skau</name>
    <birthyear>1986</birthyear>
    <deathyear/>
    <birthplace>Kolding</birthplace>
    <country>Danmark</country>
    <language>Dansk</language>
    <bio>Lærer</bio>
  </author>
  <author>
    <name>Morten Due</name>
    <birthyear>1998</birthyear>
    <deathyear/>
    <birthplace>Flensborg</birthplace>
    <country>Tyskland</country>
    <language>Tysk</language>
    <bio>Tysker</bio>
  </author>
</authors>
